# SPDX-FileCopyrightText: 2019 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: Unlicense

# Default hindent config used in Serokell.
indent-size: 2
line-length: 80
force-trailing-newline: true
